
    fib:
        addi sp, sp , -16 # return address랑 n 저장
        sw x1, 4(sp) # return address 저장 
        sw x10, 0(sp) # n 저장
        
        #sw      ra, 8(sp)       # 리턴 주소 저장
        #sw      s0, 0(sp)       # s0 레지스터 백업

        beq x10, 0, fib0 # 0이라면 
        beq x10, 1, fib1 # 1이라면
        bge x10, 2, fib2 # 2 이상이라면

    fib2: # 2 이상
        addi    x10, x10, -1      # a0 레지스터에 n - 1 로드하여 인자로 전달
        jal     ra, fib         # fib(n - 1) 호출
        
        
        
        mv      t2, a0          # 호출 결과를 t2 레지스터에 저장
        
        addi    x10, x10, -1      # a0 레지스터에 n - 2 로드하여 인자로 전달
        jal     ra, fib         # fib(n - 2) 호출
        mv      t3, a0          # 호출 결과를 t3 레지스터에 저장

        mul     a0, t2, t3      # fib(n - 1) * fib(n - 2) 계산
        j       return          # 결과 리턴하고 함수 종료

    fib1:
        addi x10, x0, 1 # return value를 x10에 저장함
        j return

    fib0:
        addi x10, x0, x0
        j return

    return:
        addi sp, sp, 16
        jalr x0, 0(x1)



    int fib(int n){
        if (n==0) return 0;
        else if(n==1) return 1;
        else return fib(n-1)*fib(n-2)
    }